### ISSUE TITLE
Graph Selection in OSSMC plugin

### ISSUE THREAD

**Issue by ferhoyos** [kiali/openshift-servicemesh-plugin#173]
Now that PFT graph has been added to Kiali code, it is time to be able to select between Cytoscape and PFT graph in the OSSMC plugin. PFT graph should be the default option.

**Comment by leandroberetta** [comment]
> To do this we need to set `spec.kiali_feature_flags.ui_defaults.graph.impl: pf`

One doubt I have is, as far as I know, there is just one Kiali CR (the one that installs the Kiali server), and then there is a CR for the plugin, if we configured the CR to use the PF impl, both Kiali standalone and plugin will use the PF impl. Perhaps thata is OK for OpenShift going forward, but just wanted to ask about this situation, because at first I thought this would be enable by default just for the plugin.

**Comment by jmazzitelli** [comment]
> Then we don't need to complex installation procedure with multiple Kiali instances.

I agree... If the UI itself can tell the server-side how to generate the graph ("cy" vs. "pf"), then, yes, definitely do that.
