### ISSUE TITLE
Plugin time interval+refresh controls on detail pages

### ISSUE THREAD

**Issue by lucasponce** [kiali/openshift-servicemesh-plugin#42]
Kiali incorporates the time controls (interval and refresh selection) as part of the common design shared by all pages, including details:
![image](https://user-images.githubusercontent.com/1662329/177529800-b8f6826f-34b0-4c75-998a-3ede59c1c5c2.png)

But in the context of the plugin layout, these controls have been omitted to facilitate the integration with the common elements of the OpenShift Console:
![image](https://user-images.githubusercontent.com/1662329/177530387-439c8099-e129-4337-9a34-85c5e4c7a506.png)

The "Service Mesh" tabs require alternative "time controls" for this particular context.

This topic has been discussed with @andrew-ronaldson and there could be several options to consider:
![image](https://user-images.githubusercontent.com/1662329/177530918-570a7fcd-e5b1-4593-a31e-370342f319a6.png)

One possibility could be to have something closer to the "minigraph" timestamp (that opens a small modal to allow the user to select/change the time selection and refresh), or also to add an action in the "minigraph" kebap.

Perhaps one can be more visible for users but in any case, the goal of this issue is to discuss this topic, get feedback from UX / @andrew-ronaldson about what could be the best option, and implement this alternative that should be available only on this context.

The issue is created under the plugin, but the work would require changes in the kiali UI (just to follow the introduced pattern of conditional rendering when the "parent kiosk" mode is active).

**Comment by andrew-ronaldson** [comment]
![Screen Shot 2022-08-11 at 12 18 02 PM](https://user-images.githubusercontent.com/28658548/184168727-3d86a088-bf53-4a02-9d59-f18e67789ad5.png)
I was thinking something like this screenshot. Add the clock icon and make the text clickable to open a modal with the time range controls. This option would need a tooltip to show the full time detail because of the truncation.
Alternatively, we could have the time range dropdown option to select from the defaults or a custom range with the modal. The con of that is it doesn't display the full time info.

**Comment by israel-hdez** [comment]
Making the time range clickable and showing a modal sounds fine.

My question is: where to accommodate the time controls in the other tabs? The time controls are common for all the Overview, Traffic, Inbound metrics and Traces tab (that's what is available for "Services"). That's the reason why those controls are currently at the top. By removing the time controls from the top and bringing them inside the Overview tab, we may also need to add these controls inside the other tabs (although, probably on the other tabs it is more straigh forward, because those have toolbars).

> This option would need a tooltip to show the full time detail because of the truncation.

@andrew-ronaldson I think I don't understand this sentence. What should have a tooltip, and what would be truncated?

**Comment by israel-hdez** [comment]
@lucasponce I have a question. In your main comment, I see you wrote that _this alternative that should be available only on this context._ Does that mean that what is being discussed here should only affect the "parent kiosk" mode, while the standalone Kiali should remain unchanged?

**Comment by lucasponce** [comment]
> Does that mean that what is being discussed here should only affect the "parent kiosk" mode, while the standalone Kiali should remain unchanged?

Correct. The "standalone" mode should not change. All these features should be under a conditional logic that detects the "kiosk" mode, similar to that implemented for links.

**Comment by israel-hdez** [comment]
Closing, as I think this is now complete.
